// One C function per binding slot. Written with the preprocessor: three hex
// digits give SWIFTPY_THUNK_COUNT thunks, named and numbered by the digits.
#include "Python.h"
#include "Cthunks.h"

#define SWIFTPY_THUNK(X, Y, Z) \
    static PyObject *swiftpy_thunk_##X##Y##Z(PyObject *self, PyObject *args) { \
        return (PyObject *)swiftpy_dispatch(0x##X##Y##Z, self, args); \
    }

#define SWIFTPY_THUNK_ROW(X, Y) \
    SWIFTPY_THUNK(X, Y, 0) SWIFTPY_THUNK(X, Y, 1) SWIFTPY_THUNK(X, Y, 2) SWIFTPY_THUNK(X, Y, 3) \
    SWIFTPY_THUNK(X, Y, 4) SWIFTPY_THUNK(X, Y, 5) SWIFTPY_THUNK(X, Y, 6) SWIFTPY_THUNK(X, Y, 7) \
    SWIFTPY_THUNK(X, Y, 8) SWIFTPY_THUNK(X, Y, 9) SWIFTPY_THUNK(X, Y, a) SWIFTPY_THUNK(X, Y, b) \
    SWIFTPY_THUNK(X, Y, c) SWIFTPY_THUNK(X, Y, d) SWIFTPY_THUNK(X, Y, e) SWIFTPY_THUNK(X, Y, f)

#define SWIFTPY_THUNK_PAGE(X) \
    SWIFTPY_THUNK_ROW(X, 0) SWIFTPY_THUNK_ROW(X, 1) SWIFTPY_THUNK_ROW(X, 2) SWIFTPY_THUNK_ROW(X, 3) \
    SWIFTPY_THUNK_ROW(X, 4) SWIFTPY_THUNK_ROW(X, 5) SWIFTPY_THUNK_ROW(X, 6) SWIFTPY_THUNK_ROW(X, 7) \
    SWIFTPY_THUNK_ROW(X, 8) SWIFTPY_THUNK_ROW(X, 9) SWIFTPY_THUNK_ROW(X, a) SWIFTPY_THUNK_ROW(X, b) \
    SWIFTPY_THUNK_ROW(X, c) SWIFTPY_THUNK_ROW(X, d) SWIFTPY_THUNK_ROW(X, e) SWIFTPY_THUNK_ROW(X, f)

SWIFTPY_THUNK_PAGE(0) SWIFTPY_THUNK_PAGE(1) SWIFTPY_THUNK_PAGE(2) SWIFTPY_THUNK_PAGE(3)
SWIFTPY_THUNK_PAGE(4) SWIFTPY_THUNK_PAGE(5) SWIFTPY_THUNK_PAGE(6) SWIFTPY_THUNK_PAGE(7)
SWIFTPY_THUNK_PAGE(8) SWIFTPY_THUNK_PAGE(9) SWIFTPY_THUNK_PAGE(a) SWIFTPY_THUNK_PAGE(b)
SWIFTPY_THUNK_PAGE(c) SWIFTPY_THUNK_PAGE(d) SWIFTPY_THUNK_PAGE(e) SWIFTPY_THUNK_PAGE(f)

#define SWIFTPY_THUNK_NAME(X, Y, Z) swiftpy_thunk_##X##Y##Z,

#define SWIFTPY_THUNK_NAME_ROW(X, Y) \
    SWIFTPY_THUNK_NAME(X, Y, 0) SWIFTPY_THUNK_NAME(X, Y, 1) SWIFTPY_THUNK_NAME(X, Y, 2) SWIFTPY_THUNK_NAME(X, Y, 3) \
    SWIFTPY_THUNK_NAME(X, Y, 4) SWIFTPY_THUNK_NAME(X, Y, 5) SWIFTPY_THUNK_NAME(X, Y, 6) SWIFTPY_THUNK_NAME(X, Y, 7) \
    SWIFTPY_THUNK_NAME(X, Y, 8) SWIFTPY_THUNK_NAME(X, Y, 9) SWIFTPY_THUNK_NAME(X, Y, a) SWIFTPY_THUNK_NAME(X, Y, b) \
    SWIFTPY_THUNK_NAME(X, Y, c) SWIFTPY_THUNK_NAME(X, Y, d) SWIFTPY_THUNK_NAME(X, Y, e) SWIFTPY_THUNK_NAME(X, Y, f)

#define SWIFTPY_THUNK_NAME_PAGE(X) \
    SWIFTPY_THUNK_NAME_ROW(X, 0) SWIFTPY_THUNK_NAME_ROW(X, 1) SWIFTPY_THUNK_NAME_ROW(X, 2) SWIFTPY_THUNK_NAME_ROW(X, 3) \
    SWIFTPY_THUNK_NAME_ROW(X, 4) SWIFTPY_THUNK_NAME_ROW(X, 5) SWIFTPY_THUNK_NAME_ROW(X, 6) SWIFTPY_THUNK_NAME_ROW(X, 7) \
    SWIFTPY_THUNK_NAME_ROW(X, 8) SWIFTPY_THUNK_NAME_ROW(X, 9) SWIFTPY_THUNK_NAME_ROW(X, a) SWIFTPY_THUNK_NAME_ROW(X, b) \
    SWIFTPY_THUNK_NAME_ROW(X, c) SWIFTPY_THUNK_NAME_ROW(X, d) SWIFTPY_THUNK_NAME_ROW(X, e) SWIFTPY_THUNK_NAME_ROW(X, f)

static PyCFunction swiftpy_thunks[SWIFTPY_THUNK_COUNT] = {
    SWIFTPY_THUNK_NAME_PAGE(0) SWIFTPY_THUNK_NAME_PAGE(1) SWIFTPY_THUNK_NAME_PAGE(2) SWIFTPY_THUNK_NAME_PAGE(3)
    SWIFTPY_THUNK_NAME_PAGE(4) SWIFTPY_THUNK_NAME_PAGE(5) SWIFTPY_THUNK_NAME_PAGE(6) SWIFTPY_THUNK_NAME_PAGE(7)
    SWIFTPY_THUNK_NAME_PAGE(8) SWIFTPY_THUNK_NAME_PAGE(9) SWIFTPY_THUNK_NAME_PAGE(a) SWIFTPY_THUNK_NAME_PAGE(b)
    SWIFTPY_THUNK_NAME_PAGE(c) SWIFTPY_THUNK_NAME_PAGE(d) SWIFTPY_THUNK_NAME_PAGE(e) SWIFTPY_THUNK_NAME_PAGE(f)
};

void *swiftpy_thunk(int slot) {
    if (slot < 0 || slot >= SWIFTPY_THUNK_COUNT) {
        return NULL;
    }
    return (void *)swiftpy_thunks[slot];
}
